### ISSUE TITLE
multiple files

### ISSUE THREAD

**Issue by cheesycod** [gzuidhof/tygo#25]
Would it be possible to add a config option to allow types on different files to be in different ts files

e.g if theres foo.go and bar.go in a package, create foo.ts and bar.ts for types instead of one file

**Comment by gzuidhof** [comment]
This is theoretically possible, but it would require an intermediate representation in the transpiler. The reason is that if the files refer to eachother, in Typescript you would need to have them import one-another.

So, perhaps the real answer is: not really unless we change *tygo* to a large degree.
